apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-kubernetes-test
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-kubernetes-test
spec:
  selector:
    matchLabels:
      app: flask-kubernetes-test
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-kubernetes-test
    spec:
      containers:
        - name: flask-kubernetes-test
          image: docker.io/dksipl/flask-kubernetes-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
